services:
  - type: web
    name: climb-lol
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:postgres@localhost:5432/climb_lol"
      - key: NEXTAUTH_URL
        value: "https://climb.lol"
      - key: NEXTAUTH_SECRET
        value: ""
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: DISCORD_CLIENT_ID
        value: ""
      - key: DISCORD_CLIENT_SECRET
        value: ""
